### ISSUE TITLE
Convert scripts into ruby gems

### ISSUE THREAD

**Issue by athityakumar** [metakgp/mfqp-source#12]
For example , I have converted the images2pdfs script into "metakgp-images2pdfs" gem. 

This makes it easy for us to integrate scripts. Also , it provides us experience with gem-making.
Similarly , we can convert all useful scripts into "metakgp-scriptname" gems, and install all gems with "gem install metakgp-all" (I can build that gem)

We can push the source codes of the gem files into the mfqp_source/scripts repository. Any comments?

**Comment by icyflame** [comment]
Hey, I think that it's better to keep things as lightweight scripts, instead of trying to bundle them up too much. 

The whole idea of the scripts repo was to have stuff that can be used as a one-off thing. Installing Ruby and doing gem install should be enough. Gives more visibility ( especially if you use `gem install --path vendor/bundle`, which helps keep everything in one single directory which can be nuked when done.

Gems would almost do the same thing, except for not having to write `ruby script.rb` perhaps. I prefer scripts better. A clearer distinction and absolutely zero boilerplate.

What do you think, @vivekiitkgp and @nevinvalsaraj ?

**Comment by hargup** [comment]
I agree with @icyflame bundling the scripts will prevent easy reuse.
